# ### Hyprland ###
# Apps
$terminal = foot
$browser = firefox
$editor = codium
$fileExplorer = dolphin

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 0.3
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = false
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 20
$windowGapsIn = 10
$windowGapsOut = 20
$singleWindowGapsOut = 20

# Window styling
$windowOpacity = 1.0
$windowRounding = 20

$windowBorderSize = 5
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 5  # In percent
$cursorTheme = sweet-cursors
$cursorSize = 24


# ### Keybinds ###
# Workspaces
$kbMoveWinToWs = Super+Shift
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, O

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow = Super+Ctrl, C

# Special workspace toggles
$kbSystemMonitor = Super, S
$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, R

# Apps
$kbTerminal = Super, Return
$kbBrowser = Super, W
$kbEditor = Super, N
$kbFileExplorer = Super, E

# Misc
$kbSession = Super, Escape
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, K
$kbLock = Super, L
$kbRestoreLock = Super+Alt, L
